export const INCIDENT_TEMPLATES_PT = [
    {
        name: 'str.incident.template.generic',
        incidents: [
            { value: 'Tentativa de invasão', label: 'str.incident.type.intrusion.attempt', priority: 1 },
            { value: 'Veículo suspeito', label: 'str.incident.type.suspicious.vehicle', priority: 1 },
            { value: 'Sucata em local impróprio', label: 'str.incident.type.scrap.in.improper.location', priority: 3 },
            { value: 'Iluminação deficiente fundos', label: 'str.incident.type.insufficient.backlighting', priority: 3 },
            { value: 'Chuva intensa', label: 'str.incident.type.intense.rain', priority: 3 },
            { value: 'Pedido de apoio cliente', label: 'str.incident.type.client.support.request', priority: 2 },
            { value: 'Pedido de apoio portaria', label: 'str.incident.type.reception.support.request', priority: 2 },
            { value: 'Pedido de apoio administração', label: 'str.incident.type.administration.support.request', priority: 2 },
            { value: 'Extintor mal posicionado', label: 'str.incident.type.extinguisher.mispositioned', priority: 2 },
            { value: 'Extintor vencido', label: 'str.incident.type.expired.extinguisher', priority: 1 },
            { value: 'Janela aberta', label: 'str.incident.type.open.window', priority: 1 },
            { value: 'Objeto esquecido', label: 'str.incident.type.forgotten.object', priority: 3 },
            { value: 'Porta arrombada', label: 'str.incident.type.broken.door', priority: 1 },
            { value: 'Porta aberta', label: 'str.incident.type.open.door', priority: 1 },
            { value: 'Roubo', label: 'str.incident.type.robbery', priority: 1 },
            { value: 'Suspeito nas imediações', label: 'str.incident.type.suspect.in.the.area', priority: 1 },
            { value: 'Vidro quebrado', label: 'str.incident.type.broken.glass', priority: 2 },
            { value: 'Veiculo mal estacionado', label: 'str.incident.type.parked.vehicle', priority: 3 },
            { value: 'Veiculo com luz acesas', label: 'str.incident.type.vehicle.with.lights.on', priority: 3 },
            { value: 'Alta pressão caldeira', label: 'str.incident.type.high.pressure.boiler', priority: 1 },
            { value: 'Furto', label: 'str.incident.type.theft', priority: 2 },
            { value: 'Veículo aberto', label: 'str.incident.type.open.vehicle', priority: 2 },
            { value: 'Cerca elétrica rompida', label: 'str.incident.type.electric.fence.broken', priority: 1 },
            { value: 'Muro danificado', label: 'str.incident.type.damaged.wall', priority: 1 },
            { value: 'Sala acesa', label: 'str.incident.type.illuminated.room', priority: 3 },
            { value: 'Vazamento de líquidos', label: 'str.incident.type.liquid.leak', priority: 1 },
            { value: 'Roedores na área', label: 'str.incident.type.rodents.in.the.area', priority: 1 },
        ],
    },
]

export const INCIDENT_TEMPLATES_EN = [
    {
        name: 'str.incident.template.generic',
        incidents: [
            { value: 'Intrusion attempt', label: 'str.incident.type.intrusion.attempt', priority: 1 },
            { value: 'Suspicious vehicle', label: 'str.incident.type.suspicious.vehicle', priority: 1 },
            { value: 'Scrap in improper location', label: 'str.incident.type.scrap.in.improper.location', priority: 3 },
            { value: 'Insufficient backlighting', label: 'str.incident.type.insufficient.backlighting', priority: 3 },
            { value: 'Intense rain', label: 'str.incident.type.intense.rain', priority: 3 },
            { value: 'Client support request', label: 'str.incident.type.client.support.request', priority: 2 },
            { value: 'Reception support request', label: 'str.incident.type.reception.support.request', priority: 2 },
            { value: 'Administration support request', label: 'str.incident.type.administration.support.request', priority: 2 },
            { value: 'Extinguisher mispositioned', label: 'str.incident.type.extinguisher.mispositioned', priority: 2 },
            { value: 'Expired extinguisher', label: 'str.incident.type.expired.extinguisher', priority: 1 },
            { value: 'Open window', label: 'str.incident.type.open.window', priority: 1 },
            { value: 'Forgotten object', label: 'str.incident.type.forgotten.object', priority: 3 },
            { value: 'Broken door', label: 'str.incident.type.broken.door', priority: 1 },
            { value: 'Open door', label: 'str.incident.type.open.door', priority: 1 },
            { value: 'Robbery', label: 'str.incident.type.robbery', priority: 1 },
            { value: 'Suspect in the area', label: 'str.incident.type.suspect.in.the.area', priority: 1 },
            { value: 'Broken glass', label: 'str.incident.type.broken.glass', priority: 2 },
            { value: 'Parked vehicle', label: 'str.incident.type.parked.vehicle', priority: 3 },
            { value: 'Vehicle with lights on', label: 'str.incident.type.vehicle.with.lights.on', priority: 3 },
            { value: 'High pressure boiler', label: 'str.incident.type.high.pressure.boiler', priority: 1 },
            { value: 'Theft', label: 'str.incident.type.theft', priority: 2 },
            { value: 'Open vehicle', label: 'str.incident.type.open.vehicle', priority: 2 },
            { value: 'Electric fence broken', label: 'str.incident.type.electric.fence.broken', priority: 1 },
            { value: 'Damaged wall', label: 'str.incident.type.damaged.wall', priority: 1 },
            { value: 'Illuminated room', label: 'str.incident.type.illuminated.room', priority: 3 },
            { value: 'Liquid leak', label: 'str.incident.type.liquid.leak', priority: 1 },
            { value: 'Rodents in the area', label: 'str.incident.type.rodents.in.the.area', priority: 1 },
        ],
    },
]
