export const DOMAINS = [
    { value: 'ALL', label: 'str.log.domain.all' },
    { value: 'COMPANY_USER', label: 'str.log.domain.company_user' },
    { value: 'CUSTOMER_USER', label: 'str.log.domain.customer_user' },
    // { value: 'ALERT', label: 'str.log.domain.alert' },
    { value: 'PATROL-ACTION', label: 'str.log.domain.patrol_action' },
    // { value: 'PATROL', label: 'str.log.domain.patrol' },
    { value: 'COMPANY', label: 'str.log.domain.company' },
    { value: 'APPOINTMENT', label: 'str.log.domain.appointment' },
    { value: 'INCIDENT', label: 'str.log.domain.incident' },
    { value: 'PATROL-POINT', label: 'str.log.domain.patrol_point' },
    { value: 'SCHEDULE', label: 'str.log.domain.schedule' },
    { value: 'GUARD-GROUP', label: 'str.log.domain.guard_group' },
    { value: 'SITE-GROUP', label: 'str.log.domain.site_group' },
    { value: 'CLIENT-GROUP', label: 'str.log.domain.client_group' },
]
